/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  MarketContract,
  MarketContractInterface,
} from "../MarketContract";

const _abi = [
  {
    inputs: [],
    name: "participants",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x60806040526000805534801561001457600080fd5b5060b3806100236000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c80636c4470fb14602d575b600080fd5b60336047565b604051603e9190605a565b60405180910390f35b60005481565b6054816073565b82525050565b6000602082019050606d6000830184604d565b92915050565b600081905091905056fea264697066735822122014808a9c06e34001fe703fab6ace3afe8fde1f077fdc5f2890633a51cf8e6cf064736f6c63430008030033";

export class MarketContract__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<MarketContract> {
    return super.deploy(overrides || {}) as Promise<MarketContract>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): MarketContract {
    return super.attach(address) as MarketContract;
  }
  connect(signer: Signer): MarketContract__factory {
    return super.connect(signer) as MarketContract__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MarketContractInterface {
    return new utils.Interface(_abi) as MarketContractInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MarketContract {
    return new Contract(address, _abi, signerOrProvider) as MarketContract;
  }
}
