import { useState } from 'react';
import Head from 'next/head'
import { TextField } from '@ubiquitous/components';
import Countdown from 'react-countdown';
import { SITE_PREFERENCES } from '../config/constants';

export default function Home() {
  const [startCountdown, setStartCountdown] = useState(false)
  const dateOptions = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }
  const launchDate = new Date(SITE_PREFERENCES.LAUNCH_DATE).getTime()
  
  setTimeout(() => setStartCountdown(true), 250)

  return (
    <div className="min-h-screen flex flex-col justify-center items-center">
      <Head>
        <title>{ SITE_PREFERENCES.SITE_TITLE }</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-center">
        <h1 className="text-4xl">Comming soon</h1>
        <h4 className="text-2xl my-5 text-gray-700"> { new Date(SITE_PREFERENCES.LAUNCH_DATE)
                  .toLocaleDateString(SITE_PREFERENCES.LOCALE, dateOptions) } </h4>
        { startCountdown && (
          <h4 className="text-2xl">
              <Countdown date={launchDate}>
                  <p>The wait is over.</p>
              </Countdown>
          </h4>
        )}
        <TextField name="airdrop" inputType="text" placeholder="Air Drop Address" />
      </div>
    </div>
  )
}
