import { useState } from 'react';
import Head from 'next/head'
import { TextField } from '@ubiquitous/components';
import { SITE_PREFERENCES } from '../config/constants';

export default function Home() {
  // const [, setStartCountdown] = useState(false)
  const dateOptions : any = { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' }

  return (
    <div className="min-h-screen flex flex-col justify-center items-center 
      bg-black
      tracking-wide
      text-white text-shadow">
      <Head>
        <title>{ SITE_PREFERENCES.SITE_TITLE }</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="text-center">
        <h1 className="text-4xl">In curand</h1>
        <h4 className="text-xl my-5 text-gray-500">{ new Date(SITE_PREFERENCES.LAUNCH_DATE)
                  .toLocaleDateString(SITE_PREFERENCES.LOCALE, dateOptions) }</h4>
        {/* <TextField name="airdrop" inputType="text" placeholder="Air Drop Address" /> */}
      </div>
    </div>
  )
}
