import Head from 'next/head'

import { TextField } from '@ubiquitous/components';
import { SITE_PREFERENCES } from '../config/constants';

export default function Home() {
  return (
    <div>
      <Head>
        <title>{ SITE_PREFERENCES.SITE_TITLE }</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TextField name="airdrop" inputType="text" placeholder="Air Drop Address" />
    </div>
  )
}
